import express from "express";
import path from "path";
import fs from "fs";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";
import jwt from "jsonwebtoken";
import bcrypt from "bcryptjs";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

const DB_PATH = path.join(process.cwd(), "learn_dcrack_db.json");
const JWT_SECRET = process.env.JWT_SECRET || "learndcrack_secret_fallback";

// Express JWT Auth Middleware
export interface AuthenticatedRequest extends express.Request {
  user?: {
    id: string;
    email: string;
    role: "learner" | "author" | "admin";
  };
}

const authenticateJWT = (req: AuthenticatedRequest, res: express.Response, next: express.NextFunction) => {
  const authHeader = req.headers.authorization;
  if (authHeader) {
    const token = authHeader.split(" ")[1];
    jwt.verify(token, JWT_SECRET, (err, decoded: any) => {
      if (err) {
        return res.status(403).json({ error: "Invalid or expired session token" });
      }
      req.user = {
        id: decoded.id,
        email: decoded.email,
        role: decoded.role
      };
      next();
    });
  } else {
    res.status(401).json({ error: "Access token is missing" });
  }
};

// Lazy load Gemini AI Client
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      console.warn("GEMINI_API_KEY is missing, AI features will have mocked fallback responses.");
    }
    aiClient = new GoogleGenAI({
      apiKey: key || "MOCK_KEY",
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// Relational Schema Types matching MySQL expectations
interface DBUser {
  id: string;
  name: string;
  email: string;
  password: string;
  role: "learner" | "author" | "admin";
  avatar: string;
  bio: string;
  skills: string[];
  learning_interests: string[];
  streak: number;
  xp: number;
  created_at: string;
}

interface DBDomain {
  id: string;
  domain_name: string;
  description: string;
  icon: string;
  slug: string;
  tags: string[];
}

interface DBCourse {
  id: string;
  title: string;
  description: string;
  domain_id: string;
  creator_id: string;
  price: number;
  tags: string[];
  thumbnail: string;
  status: "draft" | "public";
  views: number;
  likes: number;
  enrolledCount: number;
  created_at: string;
  authorName: string;
  authorAvatar: string;
  authorTitle: string;
  authorBio: string;
}

interface DBLesson {
  id: string;
  course_id: string;
  title: string;
  content: string; // Fills Feature 5 (AI Summary can digest actual lesson text)
  module_id: string;
  module_title: string;
  duration: string;
  isLocked: boolean;
  preview: boolean;
}

interface DBEnrollment {
  id: string;
  user_id: string;
  course_id: string;
  progress: number;
  enrolled_at: string;
}

interface DBProgress {
  id: string;
  user_id: string;
  lesson_id: string;
  completion_status: "completed" | "active";
}

interface DBBookmark {
  id: string;
  user_id: string;
  course_id: string;
}

interface DBComment {
  id: string;
  userId: string;
  userName: string;
  userAvatar: string;
  isAuthor?: boolean;
  contentId: string;
  comment: string;
  likes: number;
  createdAt: string;
}

interface DBQuiz {
  id: string;
  course_id: string;
  lesson_id: string;
  questions: any[]; // List of MCQs, True/False, Short answers generated by Gemini
  created_at: string;
}

interface DBQuizHistory {
  id: string;
  user_id: string;
  quiz_id: string;
  score: number;
  total_questions: number;
  answers: Record<string, string>;
  timestamp: string;
}

interface DBActivityLog {
  id: string;
  type: "lesson_completed" | "badge_earned" | "enrolled";
  title: string;
  subtitle: string;
  timestamp: string;
}

interface DatabaseSchema {
  users: DBUser[];
  domains: DBDomain[];
  courses: DBCourse[];
  lessons: DBLesson[];
  enrollments: DBEnrollment[];
  progress: DBProgress[];
  bookmarks: DBBookmark[];
  comments: DBComment[];
  quizzes: DBQuiz[];
  quiz_history: DBQuizHistory[];
  activityLogs: DBActivityLog[];
}

// Reads and migrates files to the specified Relational MySQL structure
function readDb(): DatabaseSchema {
  try {
    if (!fs.existsSync(DB_PATH)) {
      const initialDb = writeInitialSeed();
      return initialDb;
    }
    const raw = fs.readFileSync(DB_PATH, "utf-8");
    const data = JSON.parse(raw);
    
    // Ensure separate arrays (relational simulation) exist on load
    let migrated = false;
    
    if (!data.users) { data.users = []; migrated = true; }
    if (!data.domains) { data.domains = []; migrated = true; }
    if (!data.courses) { data.courses = []; migrated = true; }
    if (!data.lessons) { data.lessons = []; migrated = true; }
    if (!data.enrollments) { data.enrollments = []; migrated = true; }
    if (!data.progress) { data.progress = []; migrated = true; }
    if (!data.bookmarks) { data.bookmarks = []; migrated = true; }
    if (!data.comments) { data.comments = []; migrated = true; }
    if (!data.quizzes) { data.quizzes = []; migrated = true; }
    if (!data.quiz_history) { data.quiz_history = []; migrated = true; }
    if (!data.activityLogs) { data.activityLogs = []; migrated = true; }

    // Migrate any legacy plain-passwords to bcrypt
    data.users.forEach((u: any) => {
      if (u.password && !u.password.startsWith("$2a$") && !u.password.startsWith("$2b$")) {
        u.password = bcrypt.hashSync(u.password, 10);
        migrated = true;
      }
      if (!u.skills) { u.skills = ["Node.js", "React"]; migrated = true; }
      if (!u.learning_interests) { u.learning_interests = ["Web Development", "AI & Machine Learning"]; migrated = true; }
    });

    // Extract dynamic Modules -> flat relational Lessons table on startup if empty
    if (data.lessons.length === 0 && data.courses && data.courses.length > 0) {
      data.courses.forEach((course: any) => {
        if (course.modules) {
          course.modules.forEach((mod: any) => {
            if (mod.lessons) {
              mod.lessons.forEach((les: any) => {
                data.lessons.push({
                  id: les.id,
                  course_id: course.id,
                  title: les.title,
                  content: generateMarkdownContentForLesson(les.id, les.title),
                  module_id: mod.id,
                  module_title: mod.title,
                  duration: les.duration || "15:00",
                  isLocked: les.isLocked ?? true,
                  preview: les.preview ?? false
                });
              });
            }
          });
          // Remove modules from core object so courses properties matches MySQL strictly
          delete course.modules;
          migrated = true;
        }
      });
    }

    // Map Domain relational keys if old attributes
    data.domains.forEach((dom: any) => {
      if (dom.name && !dom.domain_name) {
        dom.domain_name = dom.name;
        migrated = true;
      }
    });

    if (migrated) {
      fs.writeFileSync(DB_PATH, JSON.stringify(data, null, 2), "utf-8");
    }

    return data;
  } catch (error) {
    console.error("Database reading error, generating clean seed", error);
    return writeInitialSeed();
  }
}

function writeDb(data: DatabaseSchema) {
  try {
    fs.writeFileSync(DB_PATH, JSON.stringify(data, null, 2), "utf-8");
  } catch (error) {
    console.error("Failed to write to DB file", error);
  }
}

function writeInitialSeed(): DatabaseSchema {
  const sampleUsers: DBUser[] = [
    {
      id: "u1",
      name: "Alex Rivet",
      email: "alex@learndcrack.com",
      password: bcrypt.hashSync("password123", 10),
      role: "author",
      avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
      bio: "Ex-FAANG engineer specializing in high-concurrency Node.js microservices.",
      skills: ["React", "TypeScript", "Node.js", "Docker"],
      learning_interests: ["Web Development", "Cloud Architecture"],
      streak: 12,
      xp: 2450,
      created_at: new Date().toISOString()
    },
    {
      id: "u2",
      name: "Dr. Sarah Chen",
      email: "sarah@learndcrack.com",
      password: bcrypt.hashSync("password123", 10),
      role: "author",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
      bio: "Lead AI Researcher focused on LLM fine-tuning and agentic architectures.",
      skills: ["Python", "Transformers", "PyTorch", "RAG"],
      learning_interests: ["AI & Machine Learning", "Data Science"],
      streak: 9,
      xp: 1850,
      created_at: new Date().toISOString()
    },
    {
      id: "u3",
      name: "Marcus Volt",
      email: "marcus@learndcrack.com",
      password: bcrypt.hashSync("password123", 10),
      role: "learner",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
      bio: "Frontend Developer excited about crafting scalable clean design systems.",
      skills: ["Framer", "CSS", "UI/UX", "Tailwind"],
      learning_interests: ["Product Design", "Web Development"],
      streak: 15,
      xp: 3200,
      created_at: new Date().toISOString()
    },
    {
      id: "u4",
      name: "Elena Ross",
      email: "elena@learndcrack.com",
      password: bcrypt.hashSync("password123", 10),
      role: "admin",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80",
      bio: "Cybersecurity Architect and Platform Administrator for LearnDrack portal.",
      skills: ["OWASP", "K8s Secure", "PenTesting", "Consensus"],
      learning_interests: ["Cyber Security", "Cloud Architecture"],
      streak: 21,
      xp: 4120,
      created_at: new Date().toISOString()
    }
  ];

  const sampleDomains: DBDomain[] = [
    {
      id: "dom1",
      domain_name: "Web Development",
      description: "Master the full stack from high-performance React patterns to distributed backend architectures and edge computing.",
      icon: "Terminal",
      slug: "web-dev",
      tags: ["React", "Node.js", "GraphQL", "PostgreSQL", "Next.js"]
    },
    {
      id: "dom2",
      domain_name: "AI & Machine Learning",
      description: "From LLM fine-tuning to predictive analytics. Understand the math and high-performance neural architecture pipelines.",
      icon: "Brain",
      slug: "ai-ml",
      tags: ["Transformers", "PyTorch", "LLMs", "RAG", "Agentic"]
    },
    {
      id: "dom3",
      domain_name: "Cyber Security",
      description: "Offensive and defensive security strategies for the modern web, application defense, and robust cloud infrastructure.",
      icon: "ShieldAlert",
      slug: "cyber-security",
      tags: ["PenTesting", "Defensive", "OAuth Secrets", "OWASP", "K8s Secure"]
    },
    {
      id: "dom4",
      domain_name: "Product Design",
      description: "The intersection of psychology and aesthetics. Learn design systems, user behavioral research, and interactive prototyping.",
      icon: "Framer",
      slug: "product-design",
      tags: ["Design Systems", "Framer", "Typography", "Color space"]
    },
    {
      id: "dom5",
      domain_name: "Data Science",
      description: "Extracting wisdom from noise. Master distributed ETL pathways, visual representations, and statistical analytics.",
      icon: "BarChart3",
      slug: "data-science",
      tags: ["Python", "Pandas", "D3.js", "Data Lakes"]
    },
    {
      id: "dom6",
      domain_name: "Cloud Architecture",
      description: "AWS, Azure, and GCP. Master serverless deployments, container orchestrations with Kubernetes, and global routing systems.",
      icon: "Cloud",
      slug: "cloud-architecture",
      tags: ["AWS", "Docker", "Kubernetes", "Serverless", "Terraform"]
    }
  ];

  const sampleCourses: DBCourse[] = [
    {
      id: "c1",
      title: "Mastering Distributed Systems Architectures",
      description: "In this deep dive, we explore the intricate world of distributed systems. This isn't just about microservices; it's about consensus, horizontal scale and fault metrics.",
      domain_id: "dom1",
      creator_id: "u1",
      price: 129.00,
      tags: ["RESONANCE", "ADVANCED", "Raft", "Paxos", "CAP Theorem"],
      thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=400&q=80",
      status: "public",
      views: 12400,
      likes: 382,
      enrolledCount: 3844,
      created_at: new Date().toISOString(),
      authorName: "Alex Rivet",
      authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
      authorTitle: "Principal Systems Architect",
      authorBio: "With over 15 years experience, Alex specializes in high-availability backend cluster architecture."
    },
    {
      id: "c2",
      title: "Mastering Cloud Scalability",
      description: "Learn how to build bulletproof cloud environments that scale and route traffic intelligently across microservice endpoints.",
      domain_id: "dom6",
      creator_id: "u1",
      price: 99.00,
      tags: ["AWS ARCHITECTURE", "ADVANCED", "Kubernetes", "Scalability"],
      thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80",
      status: "public",
      views: 9400,
      likes: 212,
      enrolledCount: 1540,
      created_at: new Date().toISOString(),
      authorName: "Alex Rivet",
      authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
      authorTitle: "Systems Master",
      authorBio: "Ex-FAANG cloud deployer specialized in infrastructure scaling."
    }
  ];

  const sampleLessons: DBLesson[] = [
    {
      id: "l1",
      course_id: "c1",
      title: "What is a Distributed System?",
      content: generateMarkdownContentForLesson("l1", "What is a Distributed System?"),
      module_id: "m1",
      module_title: "Module 1: Foundations of Distribution",
      duration: "12:04",
      isLocked: false,
      preview: true
    },
    {
      id: "l2",
      course_id: "c1",
      title: "The CAP Theorem Revisited",
      content: generateMarkdownContentForLesson("l2", "The CAP Theorem Revisited"),
      module_id: "m1",
      module_title: "Module 1: Foundations of Distribution",
      duration: "18:22",
      isLocked: true,
      preview: false
    },
    {
      id: "l10",
      course_id: "c2",
      title: "Hypervisors and Autoscaling groups",
      content: generateMarkdownContentForLesson("l10", "Hypervisors and Autoscaling groups"),
      module_id: "m4",
      module_title: "Module 1: Scaling VM Clusters",
      duration: "18:00",
      isLocked: false,
      preview: true
    }
  ];

  const initialDb: DatabaseSchema = {
    users: sampleUsers,
    domains: sampleDomains,
    courses: sampleCourses,
    lessons: sampleLessons,
    enrollments: [
      {
        id: "en1",
        user_id: "u1",
        course_id: "c1",
        progress: 33,
        enrolled_at: new Date().toISOString()
      },
      {
        id: "en2",
        user_id: "u3",
        course_id: "c2",
        progress: 100,
        enrolled_at: new Date().toISOString()
      }
    ],
    progress: [
      { id: "p1", user_id: "u1", lesson_id: "l1", completion_status: "completed" }
    ],
    bookmarks: [
      { id: "b1", user_id: "u1", course_id: "c2" }
    ],
    comments: [
      {
        id: "comment1",
        userId: "u3",
        userName: "Marcus Volt",
        userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
        contentId: "c1",
        comment: "Excellent breakdown on Raft split brain scenarios!",
        likes: 5,
        createdAt: new Date().toISOString()
      }
    ],
    quizzes: [],
    quiz_history: [
      {
        id: "qh1",
        user_id: "u1",
        quiz_id: "qz_static1",
        score: 4,
        total_questions: 5,
        answers: {},
        timestamp: new Date().toISOString()
      }
    ],
    activityLogs: [
      {
        id: "act1",
        type: "lesson_completed",
        title: "Completed lesson \"What is a Distributed System?\"",
        subtitle: "in Mastering Distributed Systems",
        timestamp: "Today, 10:24 AM"
      }
    ]
  };

  fs.writeFileSync(DB_PATH, JSON.stringify(initialDb, null, 2), "utf-8");
  return initialDb;
}

function generateMarkdownContentForLesson(id: string, title: string): string {
  if (id === "l1") {
    return `# What is a Distributed System? \n\nA distributed system is an architectural paradigm where multiple separate node points run across isolated processors and sync exclusively via asynchronous packet transactions.\n\n## Core Characteristics\n1. **Concurrency of Components**: Multiple servers process requests concurrently.\n2. **No General Clock**: Nodes have their local clocks drift. Synchronization calls require logical timestamps like Lamport Clocks.\n3. **Independent Failures**: Individual servers will crash while the global cluster stays online.\n\n### Code Snippet Example: Sockets Handshake\n\`\`\`javascript\nconst net = require("net");\nconst server = net.createServer((socket) => {\n  socket.write("TCP packet handshake received\\n");\n});\nserver.listen(4000);\n\`\`\``;
  }
  if (id === "l2") {
    return `# The CAP Theorem Revisited\n\nThe Brewer's CAP Theorem is a crucial guide in high-performance system configuration.\n\n## The Axioms\nDevelopers must formulate trade-offs around three core pillars:\n- **Consistency**: All reading queries access the absolute latest state mutation.\n- **Availability**: Every healthy container returns a non-error code status.\n- **Partition Tolerance**: The system survives network partition splits.\n\n### CAP Matrix Selection\nUse **CP** for ledger-based transfers where consistency is vital. Use **AP** for timeline news feeds to allow instant user reading access.`;
  }
  return `# ${title}\n\nThis lesson provides a deep masterclass in system engineering concepts. Check out our summary and key points to highlight important terms.\n\n### Structural Design Objectives\n- Maximize availability metrics across regions.\n- Minimizes synchronization locking over shared datastores.\n- Optimize response times.`;
}

// REST API handlers

// User Register
app.post("/api/auth/register", (req, res) => {
  const { name, email, password, role, skills, learning_interests } = req.body;
  if (!name || !email || !password) {
    return res.status(400).json({ error: "Missing required fields" });
  }

  const db = readDb();
  if (db.users.find(u => u.email.toLowerCase() === email.toLowerCase())) {
    return res.status(400).json({ error: "Email is already registered" });
  }

  const defaultAvatar = `https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80`;

  const newUser: DBUser = {
    id: "u_" + Math.random().toString(36).substring(2),
    name,
    email: email.toLowerCase(),
    password: bcrypt.hashSync(password, 10),
    role: role || "learner",
    avatar: defaultAvatar,
    bio: "",
    skills: skills || [],
    learning_interests: learning_interests || [],
    streak: 1,
    xp: 100,
    created_at: new Date().toISOString()
  };

  db.users.push(newUser);
  writeDb(db);

  // Generate JWT Token
  const token = jwt.sign({ id: newUser.id, email: newUser.email, role: newUser.role }, JWT_SECRET, { expiresIn: "7d" });

  // Safe user return (omit password)
  const { password: _, ...userNoPassword } = newUser;
  return res.json({ token, user: userNoPassword });
});

// User Login
app.post("/api/auth/login", (req, res) => {
  const { email, password } = req.body;
  if (!email || !password) {
    return res.status(400).json({ error: "Email and password are required" });
  }

  const db = readDb();
  const user = db.users.find(u => u.email.toLowerCase() === email.toLowerCase());
  
  if (!user) {
    return res.status(401).json({ error: "Invalid email or password credentials" });
  }

  const valid = bcrypt.compareSync(password, user.password);
  if (!valid) {
    return res.status(401).json({ error: "Invalid email or password credentials" });
  }

  // Increment login streak on consecutive logins is tracked on client dashboard
  user.streak = (user.streak || 1) + 1;
  writeDb(db);

  const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, JWT_SECRET, { expiresIn: "7d" });
  const { password: _, ...userNoPassword } = user;
  return res.json({ token, user: userNoPassword });
});

// Forgot Password
app.post("/api/auth/forgot-password", (req, res) => {
  const { email } = req.body;
  if (!email) {
    return res.status(400).json({ error: "Email is required" });
  }

  const db = readDb();
  const user = db.users.find(u => u.email.toLowerCase() === email.toLowerCase());
  if (!user) {
    return res.status(404).json({ error: "Account not found with this email" });
  }

  // Generate simulated secure recovery URL
  return res.json({
    success: true,
    message: "Recovery dispatch initiated. A reset link has been compiled and dispatched.",
    recoveryLink: `https://learndcrack.com/auth/reset-password?uid=${user.id}&token=sim_${Math.random().toString(36).substring(2)}`
  });
});

// Get logged user info (Session validation)
app.get("/api/auth/me", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const db = readDb();
  const user = db.users.find(u => u.id === req.user?.id);
  if (!user) {
    return res.status(404).json({ error: "User session not found" });
  }
  const { password: _, ...userNoPassword } = user;
  res.json(userNoPassword);
});

// Update Profile
app.post("/api/profile/update", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const { name, bio, avatar, skills, learning_interests, email } = req.body;
  const db = readDb();
  const user = db.users.find(u => u.id === req.user?.id);
  if (!user) {
    return res.status(404).json({ error: "User not found" });
  }

  if (name) user.name = name;
  if (bio !== undefined) user.bio = bio;
  if (avatar) user.avatar = avatar;
  if (skills !== undefined) user.skills = Array.isArray(skills) ? skills : skills.split(",").map((s: string) => s.trim()).filter(Boolean);
  if (learning_interests !== undefined) user.learning_interests = Array.isArray(learning_interests) ? learning_interests : learning_interests.split(",").map((i: string) => i.trim()).filter(Boolean);
  if (email && email.toLowerCase() !== user.email) {
    const emailExists = db.users.some(u => u.id !== user.id && u.email.toLowerCase() === email.toLowerCase());
    if (emailExists) {
      return res.status(400).json({ error: "Email address is already taken" });
    }
    user.email = email.toLowerCase();
  }

  user.xp = (user.xp || 100) + 50; // Award profile-update XP!

  writeDb(db);
  const { password: _, ...safeUser } = user;
  res.json({ success: true, user: safeUser });
});

// Domain Routes
app.get("/api/domains", (req, res) => {
  const db = readDb();
  res.json(db.domains);
});

app.post("/api/domains", authenticateJWT, (req: AuthenticatedRequest, res) => {
  if (req.user?.role !== "admin") {
    return res.status(403).json({ error: "Only admins can manage domains" });
  }
  const { domain_name, description, icon, tags } = req.body;
  if (!domain_name || !description) {
    return res.status(400).json({ error: "Domain name and description are requested" });
  }

  const db = readDb();
  const slug = domain_name.toLowerCase().replace(/\s+/g, "-");
  if (db.domains.some(d => d.slug === slug)) {
    return res.status(400).json({ error: "Domain already exists" });
  }

  const newDomain: DBDomain = {
    id: "dom_" + Math.random().toString(36).substring(2),
    domain_name,
    description,
    icon: icon || "Terminal",
    slug,
    tags: tags || []
  };

  db.domains.push(newDomain);
  writeDb(db);
  res.status(201).json(newDomain);
});

app.delete("/api/domains/:id", authenticateJWT, (req: AuthenticatedRequest, res) => {
  if (req.user?.role !== "admin") {
    return res.status(403).json({ error: "Only admins can delete domains" });
  }
  const db = readDb();
  const index = db.domains.findIndex(d => d.id === req.params.id);
  if (index === -1) {
    return res.status(404).json({ error: "Domain not found" });
  }
  db.domains.splice(index, 1);
  writeDb(db);
  res.json({ success: true, message: "Domain has been pruned" });
});

// Courses Queries including relational joins
app.get("/api/courses", (req, res) => {
  const db = readDb();
  
  // Reconstruct nested modules from flat lessons table for UI rendering compatibility
  const coursesWithModules = db.courses.map(course => {
    const courseLessons = db.lessons.filter(l => l.course_id === course.id);
    
    // Group lessons by module_id
    const modulesMap = new Map<string, { id: string; title: string; lessons: any[]; duration: string }>();
    
    courseLessons.forEach(les => {
      const modId = les.module_id || "m_def";
      const modTitle = les.module_title || "Module 1: Foundations";
      
      if (!modulesMap.has(modId)) {
        modulesMap.set(modId, {
          id: modId,
          title: modTitle,
          lessons: [],
          duration: "30m"
        });
      }
      
      modulesMap.get(modId)!.lessons.push({
        id: les.id,
        title: les.title,
        duration: les.duration,
        isLocked: les.isLocked,
        preview: les.preview
      });
    });

    const modules = Array.from(modulesMap.values());
    
    return {
      ...course,
      modules
    };
  });

  res.json(coursesWithModules);
});

app.get("/api/courses/:id", (req, res) => {
  const db = readDb();
  const course = db.courses.find(c => c.id === req.params.id);
  if (!course) {
    return res.status(404).json({ error: "Course not found" });
  }

  // JOIN lessons
  const courseLessons = db.lessons.filter(l => l.course_id === course.id);
  
  const modulesMap = new Map<string, { id: string; title: string; lessons: any[]; duration: string }>();
  courseLessons.forEach(les => {
    const modId = les.module_id || "m_def";
    const modTitle = les.module_title || "Module 1: Foundations";
    if (!modulesMap.has(modId)) {
      modulesMap.set(modId, { id: modId, title: modTitle, lessons: [], duration: "45m" });
    }
    modulesMap.get(modId)!.lessons.push({
      id: les.id,
      title: les.title,
      duration: les.duration,
      isLocked: les.isLocked,
      preview: les.preview,
      content: les.content // include page technical text
    });
  });

  const courseWithRelations = {
    ...course,
    modules: Array.from(modulesMap.values())
  };

  res.json(courseWithRelations);
});

// CMS Operations: Create Course
app.post("/api/courses", authenticateJWT, (req: AuthenticatedRequest, res) => {
  if (req.user?.role !== "author" && req.user?.role !== "admin") {
    return res.status(403).json({ error: "Only content creators and admins can publish courses" });
  }

  const { title, description, domainId, tags, price, thumbnail, modules } = req.body;
  if (!title || !description || !domainId) {
    return res.status(400).json({ error: "Missing required fields: title, description, or domain ID" });
  }

  const db = readDb();
  const authorUser = db.users.find(u => u.id === req.user?.id);

  const newCourse: DBCourse = {
    id: "c_" + Math.random().toString(36).substring(2),
    title,
    description,
    domain_id: domainId,
    creator_id: req.user.id,
    price: price || 0,
    tags: tags || [],
    thumbnail: thumbnail || "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=400&q=80",
    status: req.user?.role === "admin" ? "public" : "draft",
    views: 120,
    likes: 4,
    enrolledCount: 0,
    created_at: new Date().toISOString(),
    authorName: authorUser?.name || "Expert Author",
    authorAvatar: authorUser?.avatar || "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
    authorTitle: authorUser?.role === "admin" ? "Platform Administrator" : "Technical Coach",
    authorBio: authorUser?.bio || "Certified LearnDrack specialized tutor."
  };

  db.courses.push(newCourse);

  // Flat lessons transaction creation
  if (modules && Array.isArray(modules)) {
    modules.forEach(mod => {
      const module_id = mod.id || "mod_" + Math.random().toString(36).substring(2);
      if (mod.lessons && Array.isArray(mod.lessons)) {
        mod.lessons.forEach(l => {
          db.lessons.push({
            id: l.id || "l_" + Math.random().toString(36).substring(2),
            course_id: newCourse.id,
            title: l.title,
            content: l.content || generateMarkdownContentForLesson(l.id, l.title),
            module_id,
            module_title: mod.title || "Module 1",
            duration: l.duration || "15:00",
            isLocked: l.isLocked ?? true,
            preview: l.preview ?? false
          });
        });
      }
    });
  } else {
    // Scaffold default relational Lesson row
    db.lessons.push({
      id: "l_" + Math.random().toString(36).substring(2),
      course_id: newCourse.id,
      title: "Course Initialization Handbook",
      content: generateMarkdownContentForLesson("", "Course Initialization Handbook"),
      module_id: "m_def_" + newCourse.id,
      module_title: "Module 1: Introductory Syllabus",
      duration: "10:00",
      isLocked: false,
      preview: true
    });
  }

  writeDb(db);
  res.status(201).json(newCourse);
});

// CMS Operations: Edit Course
app.patch("/api/courses/:id", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const db = readDb();
  const course = db.courses.find(c => c.id === req.params.id);
  if (!course) {
    return res.status(404).json({ error: "Course not found" });
  }

  // Auth Guard: Only course author or Admin can edit
  if (course.creator_id !== req.user?.id && req.user?.role !== "admin") {
    return res.status(403).json({ error: "Access Denied: Owner authorization requested" });
  }

  const { title, description, price, tags, thumbnail, status } = req.body;
  if (title) course.title = title;
  if (description) course.description = description;
  if (price !== undefined) course.price = Number(price);
  if (tags) course.tags = tags;
  if (thumbnail) course.thumbnail = thumbnail;
  if (status) course.status = status;

  writeDb(db);
  res.json({ success: true, course });
});

// CMS Operations: Delete Course (Cascades to enrollments and lessons relational arrays)
app.delete("/api/courses/:id", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const db = readDb();
  const cIndex = db.courses.findIndex(c => c.id === req.params.id);
  if (cIndex === -1) {
    return res.status(404).json({ error: "Course not found" });
  }

  const course = db.courses[cIndex];
  if (course.creator_id !== req.user?.id && req.user?.role !== "admin") {
    return res.status(403).json({ error: "Access Denied: Owner deletion credentials required" });
  }

  // Relational cascading removals (Delete Lessons, Enrollments, progress bookmarks)
  db.courses.splice(cIndex, 1);
  db.lessons = db.lessons.filter(l => l.course_id !== req.params.id);
  db.enrollments = db.enrollments.filter(en => en.course_id !== req.params.id);
  db.bookmarks = db.bookmarks.filter(b => b.course_id !== req.params.id);

  writeDb(db);
  res.json({ success: true, message: "Course and related lessons cascading deletes successfully executed" });
});

// CMS Action adding single lesson to course
app.post("/api/courses/:id/lessons", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const db = readDb();
  const course = db.courses.find(c => c.id === req.params.id);
  if (!course) {
    return res.status(404).json({ error: "Course not found" });
  }

  if (course.creator_id !== req.user?.id && req.user?.role !== "admin") {
    return res.status(403).json({ error: "Unauthorized access" });
  }

  const { title, content, module_title, duration, preview } = req.body;
  if (!title) {
    return res.status(400).json({ error: "Lesson Title is required" });
  }

  const newLesson: DBLesson = {
    id: "l_" + Math.random().toString(36).substring(2),
    course_id: course.id,
    title,
    content: content || generateMarkdownContentForLesson("", title),
    module_id: "m_" + Math.random().toString(36).substring(2),
    module_title: module_title || "Module 1",
    duration: duration || "12:00",
    isLocked: preview ? false : true,
    preview: preview || false
  };

  db.lessons.push(newLesson);
  writeDb(db);
  res.status(201).json(newLesson);
});

// Comments list
app.get("/api/courses/:id/comments", (req, res) => {
  const db = readDb();
  const com = db.comments.filter(c => c.contentId === req.params.id);
  res.json(com);
});

app.post("/api/courses/:id/comments", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const { comment } = req.body;
  if (!comment) {
    return res.status(400).json({ error: "Comment text cannot be blank" });
  }

  const db = readDb();
  const authorUser = db.users.find(u => u.id === req.user?.id);

  const newComment: DBComment = {
    id: "com_" + Math.random().toString(36).substring(2),
    userId: req.user?.id || "u1",
    userName: authorUser?.name || "Incognito Student",
    userAvatar: authorUser?.avatar || "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
    contentId: req.params.id,
    comment,
    likes: 0,
    createdAt: new Date().toISOString()
  };

  db.comments.unshift(newComment);
  writeDb(db);
  res.json(newComment);
});

// Enrollments and bookmarks
app.get("/api/enrollments", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const db = readDb();
  const userEnrollments = db.enrollments.filter(e => e.user_id === req.user?.id);
  res.json(userEnrollments);
});

app.post("/api/enrollments", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const { contentId } = req.body;
  if (!contentId) return res.status(400).json({ error: "Missing contentId parameter" });

  const db = readDb();
  const existing = db.enrollments.find(e => e.user_id === req.user?.id && e.course_id === contentId);
  if (existing) {
    return res.json(existing);
  }

  const course = db.courses.find(c => c.id === contentId);
  if (course) {
    course.enrolledCount += 1;
  }

  const newEnrollment: DBEnrollment = {
    id: "en_" + Math.random().toString(36).substring(2),
    user_id: req.user?.id || "u1",
    course_id: contentId,
    progress: 5,
    enrolled_at: new Date().toISOString()
  };

  db.enrollments.push(newEnrollment);

  // Auto-scaffold first progress entry
  const lessons = db.lessons.filter(l => l.course_id === contentId);
  if (lessons.length > 0) {
    db.progress.push({
      id: "p_" + Math.random().toString(36).substring(2),
      user_id: req.user?.id || "u1",
      lesson_id: lessons[0].id,
      completion_status: "active"
    });
  }

  const newLog: DBActivityLog = {
    id: "act_" + Math.random().toString(36).substring(2),
    type: "enrolled",
    title: `Enrolled in "${course ? course.title : "New Domain Course"}"`,
    subtitle: "Active session initialised",
    timestamp: "Just Now"
  };
  db.activityLogs.unshift(newLog);

  writeDb(db);
  res.json(newEnrollment);
});

app.post("/api/enrollments/:id/lesson-complete", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const { lessonId } = req.body;
  const db = readDb();
  const enrollment = db.enrollments.find(e => e.id === req.params.id && e.user_id === req.user?.id);
  if (!enrollment) {
    return res.status(404).json({ error: "Enrollment record not found" });
  }

  // Create or update progress entry
  const existingProg = db.progress.find(p => p.user_id === req.user?.id && p.lesson_id === lessonId);
  if (!existingProg) {
    db.progress.push({
      id: "p_" + Math.random().toString(36).substring(2),
      user_id: req.user?.id || "u1",
      lesson_id: lessonId,
      completion_status: "completed"
    });
  } else {
    existingProg.completion_status = "completed";
  }

  // Award XP inside the relational User profile table row
  const activeUser = db.users.find(u => u.id === req.user?.id);
  if (activeUser) {
    activeUser.xp = (activeUser.xp || 100) + 20;
  }

  // Recalculate enrollment progress:
  const courseLessons = db.lessons.filter(l => l.course_id === enrollment.course_id);
  const totalLessonsCount = courseLessons.length;
  
  if (totalLessonsCount > 0) {
    const completedList = db.progress.filter(p => p.user_id === req.user?.id && p.completion_status === "completed" && courseLessons.some(l => l.id === p.lesson_id));
    enrollment.progress = Math.round((completedList.length / totalLessonsCount) * 100);
  } else {
    enrollment.progress = 100;
  }

  // Log activity
  const completedLesson = db.lessons.find(l => l.id === lessonId);
  const course = db.courses.find(c => c.id === enrollment.course_id);
  db.activityLogs.unshift({
    id: "act_" + Math.random().toString(36).substring(2),
    type: "lesson_completed",
    title: `Completed lesson "${completedLesson ? completedLesson.title : "Lesson Chapter"}"`,
    subtitle: `in ${course ? course.title : "LearnDrack Platform"}`,
    timestamp: "Just Now"
  });

  writeDb(db);
  res.json({ enrollment, xpAwarded: 20 });
});

// Bookmarks relational toggling
app.get("/api/bookmarks", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const db = readDb();
  const userBookmarks = db.bookmarks.filter(b => b.user_id === req.user?.id);
  res.json(userBookmarks);
});

app.post("/api/bookmarks", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const { courseId } = req.body;
  if (!courseId) return res.status(400).json({ error: "Missing courseId" });

  const db = readDb();
  const index = db.bookmarks.findIndex(b => b.user_id === req.user?.id && b.course_id === courseId);
  if (index !== -1) {
    db.bookmarks.splice(index, 1);
    writeDb(db);
    return res.json({ bookmarked: false, message: "Pruned from bookmarks" });
  }

  const newBookmark: DBBookmark = {
    id: "b_" + Math.random().toString(36).substring(2),
    user_id: req.user?.id || "u1",
    course_id: courseId
  };
  db.bookmarks.push(newBookmark);
  writeDb(db);
  res.json({ bookmarked: true, bookmark: newBookmark });
});

// Logs endpoint
app.get("/api/activity-logs", (req, res) => {
  const db = readDb();
  res.json(db.activityLogs);
});

// Admin view endpoints
app.get("/api/users", authenticateJWT, (req: AuthenticatedRequest, res) => {
  if (req.user?.role !== "admin") {
    return res.status(403).json({ error: "Forbidden: Admin clearance required" });
  }
  const db = readDb();
  // Safe map
  const safeUsers = db.users.map(u => {
    const { password: _, ...rest } = u;
    return rest;
  });
  res.json(safeUsers);
});

app.delete("/api/users/:id", authenticateJWT, (req: AuthenticatedRequest, res) => {
  if (req.user?.role !== "admin") {
    return res.status(403).json({ error: "Forbidden" });
  }
  const db = readDb();
  const index = db.users.findIndex(u => u.id === req.params.id);
  if (index === -1) {
    return res.status(404).json({ error: "User not found" });
  }
  db.users.splice(index, 1);
  writeDb(db);
  res.json({ success: true, message: "User deleted" });
});

// FEATURE 4: AI Quiz Generator Controller (Using Gemini models/sdk)
app.post("/api/ai/quiz-generate", async (req, res) => {
  const { courseId, lessonId } = req.body;
  if (!courseId || !lessonId) {
    return res.status(400).json({ error: "Missing courseId or lessonId parameter" });
  }

  const db = readDb();
  const lesson = db.lessons.find(l => l.id === lessonId && l.course_id === courseId);
  if (!lesson) {
    return res.status(404).json({ error: "Technical lesson not found in relational datastore" });
  }

  // Check if quiz already exists to speed up and reuse
  const existingQuiz = db.quizzes.find(q => q.lesson_id === lessonId);
  if (existingQuiz) {
    return res.json(existingQuiz);
  }

  const instruction = 
    `You are LearnDrack's chief curriculum evaluator. Generate exactly 5 highly educational questions based on this technical markdown excerpt.
     Your output must contain exactly:
     - 2 Multiple Choice Questions (MCQ) - each with 4 options and exact correct_option Index (0 to 3).
     - 2 True/False Questions - with accurate correct_option boolean (as string "True" or "False").
     - 1 Short Answer Question - with clear prompt and correct_answer keyword summary.
     Format your output STRICTLY as a raw JSON array of objects. Do not wrap in Markdown formatting fences or prefix write anything else.
     Structure schema:
     [
       {
         "id": "q1",
         "type": "mcq",
         "question": "question text",
         "options": ["A", "B", "C", "D"],
         "correct_option": 0
       },
       {
         "id": "q3",
         "type": "true_false",
         "question": "question text",
         "correct_option": "True"
       },
       {
         "id": "q5",
         "type": "short",
         "question": "question text",
         "correct_answer": "Expected exact answer keyword"
       }
     ]`;

  const prompt = `Here is our lesson material:\n\n${lesson.content}\n\nBuild the evaluation JSON array now:`;

  try {
    const ai = getGeminiClient();
    let questionsParsed: any[] = [];
    let isMock = true;

    if (process.env.GEMINI_API_KEY && process.env.GEMINI_API_KEY !== "MY_GEMINI_API_KEY") {
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: instruction,
          temperature: 0.1, // Low temperature for factual structure extraction!
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                id: { type: Type.STRING },
                type: { type: Type.STRING, description: "mcq or true_false or short" },
                question: { type: Type.STRING },
                options: { type: Type.ARRAY, items: { type: Type.STRING } },
                correct_option: { type: Type.STRING, description: "index for mcq, 'True'/'False' for boolean" },
                correct_answer: { type: Type.STRING, description: "guidance text or keyword" }
              }
            }
          }
        }
      });

      const responseText = response.text;
      if (responseText) {
        questionsParsed = JSON.parse(responseText.trim());
        isMock = false;
      }
    }

    if (questionsParsed.length === 0) {
      // Robust fallbacks matching l1, l2, l10
      if (lessonId === "l1") {
        questionsParsed = [
          { id: "q1", type: "mcq", question: "What is the primary synchronization medium of distributed systems?", options: ["Shared RAM buffers", "Socket Message passing", "PCI Express lanes", "Kernel interrupts"], correct_option: 1 },
          { id: "q2", type: "mcq", question: "Which characteristic means nodes have drifts and do not share clocks?", options: ["Independent crashes", "No global clock", "Asymmetric cores", "Horizontal routing"], correct_option: 1 },
          { id: "q3", type: "true_false", question: "Lamport logical timestamps are used to solve global node ordering without unified clocks.", correct_option: "True" },
          { id: "q4", type: "true_false", question: "If an physical computer breaks, the entire distributed cluster must go offline.", correct_option: "False" },
          { id: "q5", type: "short", question: "What word explains when computing components run simultaneously without absolute order?", correct_answer: "concurrency" }
        ];
      } else if (lessonId === "l2") {
        questionsParsed = [
          { id: "q1", type: "mcq", question: "What does CAP stand for in system engineering?", options: ["Core Availability Ports", "Concurrency Allocation Protocol", "Consistency Availability Partition-tolerance", "Consensus Assertion Packet-loss"], correct_option: 2 },
          { id: "q2", type: "mcq", question: "For high-performance financial systems, which CAP selection is favored?", options: ["CP (Consistency + Partition)", "AP (Availability + Partition)", "CA (Consistency + Availability)", "Unbuffered Transactions"], correct_option: 0 },
          { id: "q3", type: "true_false", question: "Consistency implies all global nodes view the absolute latest state mutation.", correct_option: "True" },
          { id: "q4", type: "true_false", question: "The CAP theorem claims we can easily satisfy all three axioms concurrently in a network cut.", correct_option: "False" },
          { id: "q5", type: "short", question: "What state partition selection continues returning unbuffered stale records on feeds?", correct_answer: "Availability" }
        ];
      } else {
        questionsParsed = [
          { id: "q1", type: "mcq", question: "Which property is key to testing web scaling performance?", options: ["Horizontal scaling of micro-nodes", "Color spacing styles", "Adding physical switches", "Memory garbage collection bounds"], correct_option: 0 },
          { id: "q2", type: "mcq", question: "Autoscaling groups add nodes dynamically based on tracking triggers.", options: ["Target tracking policy parameters", "Manual admin clicks", "Infinite memory limits", "Hourly timers only"], correct_option: 0 },
          { id: "q3", type: "true_false", question: "Autoscaling requires continuous telemetry monitoring of infrastructure load.", correct_option: "True" },
          { id: "q4", type: "true_false", question: "Autoscaling reduces computing costs by scaling down during idle periods.", correct_option: "True" },
          { id: "q5", type: "short", question: "What name represents virtualized machine environments running inside host hardware hypervisors?", correct_answer: "VM" }
        ];
      }
    }

    const newQuiz: DBQuiz = {
      id: "qz_" + Math.random().toString(36).substring(2),
      course_id: courseId,
      lesson_id: lessonId,
      questions: questionsParsed,
      created_at: new Date().toISOString()
    };

    db.quizzes.push(newQuiz);
    writeDb(db);

    res.json({ ...newQuiz, isMock });
  } catch (error: any) {
    console.error("AI quiz generation error:", error);
    res.status(500).json({ error: "Gemini failed formatting quiz", details: error.message });
  }
});

// Submit Quiz and Auto Evaluation
app.post("/api/quizzes/:id/submit", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const { answers } = req.body; // user answers keyed like {q1: "Option text" or "True"...}
  if (!answers) return res.status(400).json({ error: "Answer payload requested" });

  const db = readDb();
  const quiz = db.quizzes.find(q => q.id === req.params.id);
  if (!quiz) return res.status(404).json({ error: "Quiz evaluation not found" });

  let score = 0;
  const evaluationResults: any[] = [];

  quiz.questions.forEach((qObj: any) => {
    const userAns = answers[qObj.id];
    let isCorrect = false;

    if (qObj.type === "mcq") {
      const correctIdx = Number(qObj.correct_option);
      const correctAnswerText = qObj.options[correctIdx];
      isCorrect = String(userAns).trim().toLowerCase() === String(correctAnswerText).trim().toLowerCase();
      evaluationResults.push({
        id: qObj.id,
        question: qObj.question,
        type: "mcq",
        userAnswer: userAns || "Unanswered",
        correctAnswer: correctAnswerText,
        isCorrect
      });
    } else if (qObj.type === "true_false") {
      isCorrect = String(userAns).trim().toLowerCase() === String(qObj.correct_option).trim().toLowerCase();
      evaluationResults.push({
        id: qObj.id,
        question: qObj.question,
        type: "true_false",
        userAnswer: userAns || "Unanswered",
        correctAnswer: qObj.correct_option,
        isCorrect
      });
    } else if (qObj.type === "short") {
      const expectedKeyword = String(qObj.correct_answer).trim().toLowerCase();
      isCorrect = String(userAns).trim().toLowerCase().includes(expectedKeyword);
      evaluationResults.push({
        id: qObj.id,
        question: qObj.question,
        type: "short",
        userAnswer: userAns || "Unanswered",
        correctAnswer: `Should include: "${qObj.correct_answer}"`,
        isCorrect
      });
    }

    if (isCorrect) score += 1;
  });

  const percentScore = Math.round((score / quiz.questions.length) * 100);

  // Award XP inside database Users table
  const user = db.users.find(u => u.id === req.user?.id);
  const xpAward = score * 10;
  if (user) {
    user.xp = (user.xp || 100) + xpAward;
  }

  const record: DBQuizHistory = {
    id: "qh_" + Math.random().toString(36).substring(2),
    user_id: req.user?.id || "u1",
    quiz_id: quiz.id,
    score,
    total_questions: quiz.questions.length,
    answers,
    timestamp: new Date().toISOString()
  };

  db.quiz_history.push(record);
  writeDb(db);

  res.json({
    success: true,
    score,
    totalQuestions: quiz.questions.length,
    percentScore,
    xpAwarded: xpAward,
    results: evaluationResults
  });
});

// Student Quiz scores history
app.get("/api/quiz-history/:userId", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const db = readDb();
  if (req.params.userId !== req.user?.id && req.user?.role !== "admin") {
    return res.status(403).json({ error: "Access Denied" });
  }

  const history = db.quiz_history.filter(h => h.user_id === req.params.userId).map(h => {
    const quiz = db.quizzes.find(q => q.id === h.quiz_id);
    const lesson = quiz ? db.lessons.find(l => l.id === quiz.lesson_id) : null;
    return {
      ...h,
      lessonTitle: lesson ? lesson.title : "Relational Code Challenge",
      courseId: quiz ? quiz.course_id : "General Evaluation"
    };
  });

  res.json(history);
});

// FEATURE 5: AI Content Summarizer Endpoint
app.post("/api/ai/summarize", async (req, res) => {
  const { content, lessonTitle } = req.body;
  if (!content) {
    return res.status(400).json({ error: "Missing content payload to summarize" });
  }

  const prompt = 
    `Analyze this Technical Lesson Study Material: "${lessonTitle || "Syllabus Segment"}".
     Please summarize this content precisely.
     You MUST generate output formatted exactly inside clean, well-spaced markdown headings:
     
     # Executive Lesson Summary
     (2-3 sentences concise high-level abstract summary)
     
     ## Key Learning Points
     - (Crucial takeaway 1)
     - (Crucial takeaway 2)
     - (Crucial takeaway 3)
     
     ## High-Yield Revision Notes
     - (Technical highlight 1: descriptive one liner definition)
     - (Technical highlight 2: descriptive one liner definition)
     
     ## Core Concept Definitions
     Provide bold callout cards explaining standard abbreviations, formulas, or system architectural patterns used in this chapter.`;

  const inputPrompt = `Technical Excerpt:\n\n${content}\n\nPlease build the summary following guidelines:`;

  try {
    const ai = getGeminiClient();
    if (process.env.GEMINI_API_KEY && process.env.GEMINI_API_KEY !== "MY_GEMINI_API_KEY") {
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: inputPrompt,
        config: {
          systemInstruction: "You are LearnDrack's specialized master curriculum summarizer. Produce structured technical breakdowns.",
          temperature: 0.65
        }
      });

      if (response.text) {
        return res.json({ summary: response.text, isMock: false });
      }
    }

    // Static fallback summary if offline or no key (robustness!)
    const fallbackText = 
      `# Executive Lesson Summary
This segment expands on technical deployment structures of high-scalability configurations. It details structural constraints and fault metrics.

## Key Learning Points
- **Consensus Metrics**: Active node majorities maintain quorum validations during network splits.
- **Failover Thresholds**: Automatic failovers restore system integrity in sub-second limits.
- **Data Partitions**: Scalability is maximized by sharded partitions with hashing keys.

## High-Yield Revision Notes
- **Horizontal Elasticity**: The capacity to inject cluster virtual instances on demand.
- **Lamport Timestamps**: Logical monotonic logical labels replacing universal microsecond syncs.

## Core Concept Definitions
**CAP Theorem Axiom**: Systems isolated under packet cuts must make a core runtime trade-off between Consistency or Availability.`;

    res.json({ summary: fallbackText, isMock: true });

  } catch (error: any) {
    console.error("Gemini summary error:", error);
    res.status(500).json({ error: "Summarizer failed", details: error.message });
  }
});

// FEATURE 6: AI Learning Recommendations Endpoint
app.get("/api/ai/recommendations", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const db = readDb();
  const user = db.users.find(u => u.id === req.user?.id);
  if (!user) return res.status(404).json({ error: "User profile not found in relational datastore" });

  const completedEnrollments = db.enrollments.filter(e => e.user_id === user.id && e.progress >= 80);
  const completedCourses = db.courses.filter(c => completedEnrollments.some(e => e.course_id === c.id));
  const userQuizzes = db.quiz_history.filter(qh => qh.user_id === user.id);

  const completedTitles = completedCourses.map(c => c.title).join(", ") || "None yet";
  const interestsList = user.learning_interests?.join(", ") || "Web Development, Cloud Architecture, AI";
  const averageQuizScore = userQuizzes.length > 0 ? (userQuizzes.reduce((sum, h) => sum + h.score, 0) / userQuizzes.length).toFixed(1) : "N/A";

  const aiInstruction = 
    `You are LearnDrack's lead counselor. Based on the user's completed courses, quiz history, and self-reported interests, generate a professional career pathway recommendations report.
     Recommend suitable advanced technology topics to focus on.
     The format MUST be JSON with properties:
       "recommended_topics": Array of strings of related areas,
       "career_path": String (descriptive paragraph of potential field role),
       "coaching_advice": String (motivational architectural strategy advice on streak/scores).`;

  const aiPrompt = `User Stats Profile:
  - Custom Interests: ${interestsList}
  - Completed courses: ${completedTitles}
  - Completed quizzes: ${userQuizzes.length} tests (Avg Score: ${averageQuizScore}/5)
  - Profile Skills: ${user.skills?.join(", ") || "None"}

  Recommend career path and coaching Advice strictly as JSON:`;

  // We can query Gemini or return a highly optimized computed recommendation
  const sendRecommendations = (dataObj: any) => {
    // Also perform exact MySQL relational JOIN: find courses matching recommended topics/domains!
    const matchingCourses = db.courses.filter(c => {
      const matchInTags = c.tags.some(tag => dataObj.recommended_topics.some((topic: string) => topic.toLowerCase().includes(tag.toLowerCase()) || tag.toLowerCase().includes(topic.toLowerCase())));
      const matchInTitle = dataObj.recommended_topics.some((topic: string) => c.title.toLowerCase().includes(topic.toLowerCase()) || topic.toLowerCase().includes(c.title.toLowerCase()));
      return matchInTags || matchInTitle;
    });

    res.json({
      ...dataObj,
      recommendedCourses: matchingCourses.length > 0 ? matchingCourses : [db.courses[0]]
    });
  };

  const offlineFallbackRec = {
    recommended_topics: ["Distributed Consensus", "Cybersecurity Defensive Coding", "Kubernetes Scaling Orchestras"],
    career_path: `Lead Cloud Cloud Architect & High-Availability Operations Expert`,
    coaching_advice: `Your technical interests in "${interestsList}" align perfectly with advanced consensus research. We advise focusing on "Mastering Distributed Systems" to master Paxos/Raft and double your current database ${user.xp} XP points!`
  };

  if (process.env.GEMINI_API_KEY && process.env.GEMINI_API_KEY !== "MY_GEMINI_API_KEY") {
    const ai = getGeminiClient();
    ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: aiPrompt,
      config: {
        systemInstruction: aiInstruction,
        responseMimeType: "application/json",
        temperature: 0.7
      }
    }).then(response => {
      if (response.text) {
        const parsed = JSON.parse(response.text.trim());
        sendRecommendations(parsed);
      } else {
        sendRecommendations(offlineFallbackRec);
      }
    }).catch(err => {
      console.warn("Gemini Recommendations failed, falling back safely", err);
      sendRecommendations(offlineFallbackRec);
    });
  } else {
    sendRecommendations(offlineFallbackRec);
  }
});

// FEATURE 8: Complete Platform Analytics
app.get("/api/analytics", authenticateJWT, (req: AuthenticatedRequest, res) => {
  const db = readDb();
  const userId = req.user?.id || "u1";

  // 1. Student Analytics
  const userEnrollments = db.enrollments.filter(e => e.user_id === userId);
  const completedCount = userEnrollments.filter(e => e.progress >= 100).length;
  const userQuizzes = db.quiz_history.filter(h => h.user_id === userId);
  const avgQuizScore = userQuizzes.length > 0 ? (userQuizzes.reduce((sum, h) => sum + h.score, 0) / userQuizzes.length).toFixed(1) : "0.0";
  const user = db.users.find(u => u.id === userId);

  // 2. Creator Analytics (based on courses authored by user)
  const authoredCourses = db.courses.filter(c => c.creator_id === userId);
  const totalViews = authoredCourses.reduce((sum, c) => sum + (c.views || 0), 0);
  const totalEnrollmentsAcrossAuthored = authoredCourses.reduce((sum, c) => sum + (c.enrolledCount || 0), 0);
  const averageCourseRating = authoredCourses.length > 0 ? 4.8 : 0.0;

  // 3. Admin Analytics
  const totalUsers = db.users.length;
  const totalCourses = db.courses.length;
  const activeSessionCount = 4; // Simulated live concurrency metric

  res.json({
    student: {
      completedCount,
      totalEnrolled: userEnrollments.length,
      averageScore: avgQuizScore,
      streak: user?.streak || 1,
      xp: user?.xp || 100,
      quizzesTaken: userQuizzes.length
    },
    creator: {
      authoredCount: authoredCourses.length,
      totalViews,
      totalEnrollmentsAcrossAuthored,
      averageRating: averageCourseRating
    },
    admin: {
      totalUsers,
      totalCourses,
      activeUsers: activeSessionCount,
      totalEnrollments: db.enrollments.length,
      domainsCount: db.domains.length,
      quizzesGenerated: db.quizzes.length
    }
  });
});

// AI Tutor endpoints compatibility
app.post("/api/ai/tutor", async (req, res) => {
  const { topic, courseTitle, customQuery } = req.body;
  if (!topic && !customQuery) {
    return res.status(400).json({ error: "Missing topic or custom query parameter" });
  }

  const instruction = 
    `You are Elena Ross, LearnDrack's Chief AI Security Engineer.
     Explain technical engineering topics with maximum precision. Use clean Markdown formatting, direct definitions, and architectural diagrams using syntax markers. Match the user with deep analytical rigor.`;

  const prompt = customQuery 
    ? `Answering query: "${customQuery}" for course: "${courseTitle || "Advanced Technical Architectures"}"`
    : `Give a detailed, technical 150-word overview of the system component: "${topic}" in course "${courseTitle}". Format using Markdown.`;

  try {
    const ai = getGeminiClient();
    if (process.env.GEMINI_API_KEY && process.env.GEMINI_API_KEY !== "MY_GEMINI_API_KEY") {
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: instruction,
          temperature: 0.7,
        }
      });
      if (response.text) {
        return res.json({ response: response.text, isMock: false });
      }
    }

    // fallback
    res.json({
      response: `### Technical Deep-Dive: ${topic || "Computing Node Security"}\n\nThis engineering subsystem features isolated nodes connected via TCP handshakes. \n\n1. **Thread safety**: Secure state mutations using mutual exclusion wrappers.\n2. **Consistency values**: Map entries synchronized over distributed consensus loops.\n\nAsk me more to review specific logs, encryption algorithms, or scaling setups!`,
      isMock: true
    });
  } catch (err: any) {
    res.status(500).json({ error: "AI tutor offline", details: err.message });
  }
});

// Boot Server
async function startServer() {
  // Run schema and migrations checks on boot
  readDb();

  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`LearnDrack relational engine booted! Server listening on http://localhost:${PORT}`);
  });
}

startServer();
